4TO/MCGA/TPs/UAI-MCGA-SistemaTurnosMedico-master/MCGA.WebSite/Controllers/AgendaController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MCGA.Constants;
using MCGA.Entities;
using MCGA.UI.Process;
using MCGA.WebSite.Models;
using PagedList;

namespace MCGA.WebSite.Controllers
{
	[Authorize]
	public class AgendaController : Controller
	{
		private AgendaProcess process = new AgendaProcess();
		private TipoDiaProcess tipoDiaProcess = new TipoDiaProcess();
		private EspecialidadesProfesionalProcess especialidadesProfesionalProcess = new EspecialidadesProfesionalProcess();
		private EspecialidadProcess especialidadProcess = new EspecialidadProcess();
		private ProfesionalProcess profesionalProcess = new ProfesionalProcess();
		private TurnoProcess turnoProcess = new TurnoProcess();
		private AtencionProcess atencionProcess = new AtencionProcess();
		private AgendaCancelacionProcess agendaCancelacionProcess = new AgendaCancelacionProcess();

		public FileResult ExportExcel()
		{
			string[] aColumnas = { "Profesional", "Especialidad", "Día", "F. desde", "F. hasta", "H. desde", "H. hasta" };
			List<dynamic> lstDatos = process.GetAll().Select(o => new { Profesional = string.Format("{0} {1}", o.EspecialidadesProfesional.Profesional.Nombre, o.EspecialidadesProfesional.Profesional.Apellido), Especialidad = o.EspecialidadesProfesional.Especialidad.descripcion, o.TipoDia.descripcion, FechaDesde = o.fecha_desde.ToShortDateString(), FechaHasta = o.fecha_hasta.ToShortDateString(), HoraDesde = o.hora_desde.ToString(), HoraHasta = o.hora_hasta.ToString() }).ToList<dynamic>();
			return File(new Framework.ExportExcel().ExportarExcel(aColumnas, lstDatos), "application/vnd.ms-excel", "Listado de agendas.xls");
		}

		public JsonResult GetFechasDisponiblesByIdEspecialidadProfesional(int idEspecialidadProfesional = 0)
		{
			List<Agenda> listAgenda = process.GetAll().Where(o => o.EspecialidadProfesionalId == idEspecialidadProfesional && o.AgendaCancelacion.Count == 0).ToList();
			if (listAgenda.Count > 0)
			{
				List<string> listaFecha = new List<string>();
				foreach (Agenda agenda in listAgenda)
				{
					DateTime fecha = DateTime.Now.Date;// agenda.fecha_desde;

					while (fecha <= agenda.fecha_hasta)
					{
						//Ver si atiende ese dia
						if ((int)fecha.DayOfWeek == agenda.TipoDia.referenciaDayOfWeek)
						{
							//Cantidad de horas que atiende en el día
							int cantidadHoras =
								(
									new DateTime(fecha.Year, fecha.Month, fecha.Day, agenda.hora_hasta.Hours, agenda.hora_hasta.Minutes, 0)
									-
									new DateTime(fecha.Year, fecha.Month, fecha.Day, agenda.hora_desde.Hours, agenda.hora_desde.Minutes, 0)
								).Hours;

							//Verificar si ese día ya tiene todo agendado
							if (turnoProcess.GetAll().Where(o => o.Fecha == fecha && o.EspecialidadProfesionalId == idEspecialidadProfesional).Count() != cantidadHoras)
							{
								listaFecha.Add(fecha.ToString("yyyy-MM-dd"));
							}
						}
						fecha = fecha.AddDays(1);
					}
				}
				return Json(listaFecha, JsonRequestBehavior.AllowGet);
			}
			else
				return Json(null, JsonRequestBehavior.AllowGet);
		}

		public JsonResult GetHorarioDisponiblesByIdEspecialidadProfesionalFecha(int idEspecialidadProfesional, DateTime fecha)
		{
			int tipoDiaId = tipoDiaProcess.GetAll().Where(o => o.referenciaDayOfWeek == (int)fecha.DayOfWeek).FirstOrDefault().Id;
			Agenda agenda = process.GetAll().Where(o => o.EspecialidadProfesionalId == idEspecialidadProfesional && o.TipoDiaId == tipoDiaId && fecha >= o.fecha_desde && fecha <= o.fecha_hasta && o.AgendaCancelacion.Count == 0).FirstOrDefault();
			if (agenda != null)
			{
				List<dynamic> listaHora = new List<dynamic>();
				TimeSpan hora =  agenda.hora_desde;
				while (hora <= agenda.hora_hasta)
				{
					//ver si hay turno con esa hora y fecha
					if (turnoProcess.GetAll().FirstOrDefault(o=> o.Fecha == fecha && o.Hora == hora && o.EspecialidadProfesionalId == idEspecialidadProfesional) == null)
					{ 
						listaHora.Add(new
						{
							HoraText = hora.ToString(@"hh\:mm"),
							HoraValue = hora.ToString(@"hh\:mm")
						});
					}
					hora = hora.Add(new TimeSpan(1, 0, 0));
				}
				return Json(listaHora, JsonRequestBehavior.AllowGet);
			}
			else
				return Json(null, JsonRequestBehavior.AllowGet);
	}
		// GET: Agenda
		[Route("listado-agenda", Name = AgendaControllerRoute.GetIndex)]
		public ActionResult Index(int? page)
        {
			var agenda = process.GetAll();
			int pageSize = int.Parse(ConfigurationManager.AppSettings.Get("CantidadFilasPagina"));
			int pageNumber = (page ?? 1);
			return View(agenda.ToPagedList(pageNumber, pageSize));
        }

		// GET: Agenda/Create
		[Route("agregar-agenda", Name = AgendaControllerRoute.GetCreate)]
		public ActionResult Create()
        {
			ViewBag.ProfesionalId = string.Empty;
			ViewBag.EspecialidadTexto = string.Empty;
			ViewBag.ProfesionalTexto = string.Empty;
			ViewBag.TipoDiaId = new SelectList(tipoDiaProcess.GetAll(), "Id", "descripcion");
            return View();
        }

        // POST: Agenda/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
		[Route("agregar-agenda", Name = AgendaControllerRoute.PostCreate)]
		public ActionResult Create([Bind(Include = "Id,EspecialidadProfesionalId,TipoDiaId,fecha_desde,fecha_hasta,hora_desde,hora_hasta")] Agenda agenda, int profesionalId)
        {
            if (ModelState.IsValid)
            {
				process.Add(agenda);
                return RedirectToAction("Index");
            }
			EspecialidadesProfesional especialidadesProfesional = especialidadesProfesionalProcess.GetById(agenda.EspecialidadProfesionalId);
			Profesional profesional = profesionalProcess.GetById(profesionalId);
			string especialidadTexto = string.Empty;
			string profesionalTexto = profesional != null ? string.Format("{0} {1}", profesional.Nombre, profesional.Apellido) : string.Empty;
			ViewBag.ProfesionalId = profesionalId.ToString();
			if (especialidadesProfesional != null)
			{ 
				Especialidad especialidad = especialidadProcess.GetById(especialidadesProfesional.EspecialidadId);
				especialidadTexto = especialidad.descripcion;
			}
			ViewBag.EspecialidadTexto = especialidadTexto;
			ViewBag.ProfesionalTexto = profesionalTexto;

			ViewBag.TipoDiaId = new SelectList(tipoDiaProcess.GetAll(), "Id", "descripcion", agenda.TipoDiaId);
            return View(agenda);
        }

		// GET: Agenda/Edit/5
		[Route("editar-agenda", Name = AgendaControllerRoute.GetEdit)]
		public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Agenda agenda = process.GetById(id);
			if (agenda == null)
            {
                return HttpNotFound();
            }
			EspecialidadesProfesional especialidadesProfesional = especialidadesProfesionalProcess.GetById(agenda.EspecialidadProfesionalId);
			Profesional profesional = profesionalProcess.GetById(agenda.EspecialidadesProfesional.ProfesionalId);
			Especialidad especialidad = especialidadProcess.GetById(especialidadesProfesional.EspecialidadId);
			string especialidadTexto = especialidad.descripcion;
			string profesionalTexto = profesional != null ? string.Format("{0} {1}", profesional.Nombre, profesional.Apellido) : string.Empty;
			ViewBag.ProfesionalId = profesional.Id.ToString();
			ViewBag.EspecialidadTexto = especialidadTexto;
			ViewBag.ProfesionalTexto = profesionalTexto;
            ViewBag.TipoDiaId = new SelectList(tipoDiaProcess.GetAll(), "Id", "descripcion", agenda.TipoDiaId);
            return View(agenda);
        }

        // POST: Agenda/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
		[Route("editar-agenda", Name = AgendaControllerRoute.PostEdit)]
		public ActionResult Edit([Bind(Include = "Id,EspecialidadProfesionalId,TipoDiaId,fecha_desde,fecha_hasta,hora_desde,hora_hasta")] Agenda agenda, int profesionalId)
        {
            if (ModelState.IsValid)
            {
				process.Edit(agenda);
                return RedirectToAction("Index");
            }
			EspecialidadesProfesional especialidadesProfesional = especialidadesProfesionalProcess.GetById(agenda.EspecialidadProfesionalId);
			Profesional profesional = profesionalProcess.GetById(profesionalId);
			string especialidadTexto = string.Empty;
			string profesionalTexto = profesional != null ? string.Format("{0} {1}", profesional.Nombre, profesional.Apellido) : string.Empty;
			ViewBag.ProfesionalId = profesionalId.ToString();
			if (especialidadesProfesional != null)
			{
				Especialidad especialidad = especialidadProcess.GetById(especialidadesProfesional.EspecialidadId);
				especialidadTexto = especialidad.descripcion;
			}
			ViewBag.EspecialidadTexto = especialidadTexto;
			ViewBag.ProfesionalTexto = profesionalTexto;
			ViewBag.TipoDiaId = new SelectList(tipoDiaProcess.GetAll(), "Id", "descripcion", agenda.TipoDiaId);
            return View(agenda);
        }

		// GET: Agenda/Delete/5
		[Route("eliminar-agenda", Name = AgendaControllerRoute.GetDelete)]
		public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Agenda agenda = process.GetById(id);
			if (agenda == null)
            {
                return HttpNotFound();
            }
            return View(agenda);
        }

        // POST: Agenda/Delete/5
        [HttpPost, ActionName("Delete")]

4TO/MCGA/TPs/UAI-MCGA-SistemaTurnosMedico-master/MCGA.WebSite/Views/Agenda/Cancelar.cshtml
@model MCGA.Entities.Agenda
@{
    ViewBag.Title = "Cancelar agenda";
    ViewBag.Description = "En esta página vamos a poder cancelar agendas del sistema.";
    ViewBag.Author = Application.Name;
    ViewBag.ReferrerMode = ReferrerMode.OriginWhenCrossOrigin;
    ViewBag.TwitterCard = new SummaryLargeImageTwitterCard("@TwitterCard");
    ViewBag.OpenGraph = new OpenGraphBusiness(
        ViewBag.Title,
        new OpenGraphImage(Url.AbsoluteContent("~/fonts/icons/open-graph-1200x630.png")) { Height = 630, Type = ContentType.Png, Width = 1200 },
        new OpenGraphContactData(Application.StreetAddress, Application.Locality, Application.PostalCode, Application.Country)
        {
            Email = Application.Email,
            Phone = Application.Phone,
            Website = Url.AbsoluteRouteUrl(AgendaControllerRoute.GetCancelar)
        },
        new OpenGraphLocation(Application.Latitude, Application.Longitude))
    {
        Determiner = OpenGraphDeterminer.Blank,
        SiteName = Application.Name
    };
}

<h2>Cancelar <small>agenda</small></h2>

<h3>¿Estás seguro?</h3>
<hr class="hrSinMarginTop" />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="content-personalizado">

        <dl class="dl-horizontal">
            <dt>
                @Html.Raw("Profesional")
            </dt>

            <dd>
                @Html.DisplayFor(model => model.EspecialidadesProfesional.Profesional.Nombre)
                @Html.DisplayFor(model => model.EspecialidadesProfesional.Profesional.Apellido)
            </dd>


            <dt>
                @Html.DisplayNameFor(model => model.EspecialidadProfesionalId)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.EspecialidadesProfesional.Especialidad.descripcion)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.TipoDiaId)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TipoDia.descripcion)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.fecha_desde)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.fecha_desde)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.fecha_hasta)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.fecha_hasta)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.hora_desde)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.hora_desde)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.hora_hasta)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.hora_hasta)
            </dd>

            <dt>
                @Html.Raw("Motivo")
            </dt>

            <dd>
                @Html.Editor("detalleCancelacion", new { htmlAttributes = new { @class = "form-control" } })
            </dd>

        </dl>



        <div class="form-group text-left paddingLeftRight_15">
            <div class="form-actions no-color">
                <button type="submit" class="btn btn-danger">
                    <i class="fa fa-calendar-times-o"></i>
                    Cancelar agenda
                </button>
            </div>
        </div>


       

        <div>
            <a class="btn btn-sm" href="@Url.Action("Index", "Agenda")">
                <i class="fa fa-chevron-circle-left"></i>
                Volver al listado
            </a>
        </div>
    </div>
}

4TO/MCGA/TPs/UAI-MCGA-SistemaTurnosMedico-master/MCGA.WebSite/Views/Agenda/Create.cshtml
@model MCGA.Entities.Agenda
@{
    ViewBag.Title = "Agenda";
    ViewBag.Description = "En esta página vamos a poder agregar agendas del sistema.";
    ViewBag.Author = Application.Name;
    ViewBag.ReferrerMode = ReferrerMode.OriginWhenCrossOrigin;
    ViewBag.TwitterCard = new SummaryLargeImageTwitterCard("@TwitterCard");
    ViewBag.OpenGraph = new OpenGraphBusiness(
        ViewBag.Title,
        new OpenGraphImage(Url.AbsoluteContent("~/fonts/icons/open-graph-1200x630.png")) { Height = 630, Type = ContentType.Png, Width = 1200 },
        new OpenGraphContactData(Application.StreetAddress, Application.Locality, Application.PostalCode, Application.Country)
        {
            Email = Application.Email,
            Phone = Application.Phone,
            Website = Url.AbsoluteRouteUrl(AgendaControllerRoute.GetCreate)
        },
        new OpenGraphLocation(Application.Latitude, Application.Longitude))
    {
        Determiner = OpenGraphDeterminer.Blank,
        SiteName = Application.Name
    };
}
<h2>Nueva <small>agenda</small> </h2>

<hr class="hrSinMarginTop" />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal content-personalizado">

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.Label("Profesional", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBox("BuscarProfesional", (String)ViewBag.ProfesionalTexto,
            new
            {
                @class = "form-control",
                autocomplete = "off",
                placeholder = "Ingrese el profesional",
            })
            @Html.Hidden("ProfesionalId", (String)ViewBag.ProfesionalId)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EspecialidadProfesionalId, null, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBox("BuscarEspecialidad", (String)ViewBag.EspecialidadTexto,
            new
            {
                @class = "form-control",
                autocomplete = "off",
                placeholder = "Ingrese la especialidad",
            })
            @Html.ValidationMessageFor(model => model.EspecialidadProfesionalId, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.EspecialidadProfesionalId)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TipoDiaId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("TipoDiaId", null, "-Seleccionar día-", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.TipoDiaId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.fecha_desde, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.fecha_desde, new { htmlAttributes = new { @class = "form-control", @min = "1900-01-01" } })
            @Html.ValidationMessageFor(model => model.fecha_desde, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.fecha_hasta, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.fecha_hasta, new { htmlAttributes = new { @class = "form-control", @min = "1900-01-01" } })
            @Html.ValidationMessageFor(model => model.fecha_hasta, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.hora_desde, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.hora_desde, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.hora_desde, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.hora_hasta, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.hora_hasta, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.hora_hasta, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group text-right paddingLeftRight_15">
        <button type="submit" class="btn btn-primary">
            <i class="fa fa-check-circle"></i>
            Guardar
        </button>
    </div>
</div>

}

<div>
    <a class="btn btn-sm" href="@Url.Action("Index", "Agenda")">
        <i class="fa fa-chevron-circle-left"></i>
        Volver al listado
    </a>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $("#BuscarEspecialidad").autocomplete({
            autoSelect: true,
            autoFocus: true,
            minLength: 1,
            source: function (request, response) {
                $.ajax({
                    url: '@Url.Action("GetEspecialidadProfesionalByProfesional", "EspecialidadesProfesional")',
                    datatype: "json",
                    data: { Areas: '', term: request.term, idProfesional: $("#ProfesionalId").val() },
                    success: function (data) {

                        response($.map(data, function (val, item) {
                            return { label: val.Name, value: val.Name, Id: val.Id };
                        }));
                    }
                });
            },
            select: function (event, ui) {
                $("#EspecialidadProfesionalId").val(ui.item.Id);
            }
        });

        $("#BuscarProfesional").autocomplete({
            autoSelect: true,
            autoFocus: true,
            minLength: 1,
            source: function (request, response) {
                $.ajax({
                    url: '@Url.Action("GetProfesional", "Profesional")',
                    datatype: "json",
                    data: { Areas: '', term: request.term },
                    success: function (data) {
                        response($.map(data, function (val, item) {
                            return { label: val.Name, value: val.Name, Id: val.Id };
                        }));
                    }
                });
            },
            select: function (event, ui) {
                $("#ProfesionalId").val(ui.item.Id);
            }
        });
    </script>
}

4TO/MCGA/TPs/UAI-MCGA-SistemaTurnosMedico-master/MCGA.WebSite/Views/Agenda/Delete.cshtml
@model MCGA.Entities.Agenda
@{
    ViewBag.Title = "Agenda";
    ViewBag.Description = "En esta página vamos a poder eliminar agendas del sistema.";
    ViewBag.Author = Application.Name;
    ViewBag.ReferrerMode = ReferrerMode.OriginWhenCrossOrigin;
    ViewBag.TwitterCard = new SummaryLargeImageTwitterCard("@TwitterCard");
    ViewBag.OpenGraph = new OpenGraphBusiness(
        ViewBag.Title,
        new OpenGraphImage(Url.AbsoluteContent("~/fonts/icons/open-graph-1200x630.png")) { Height = 630, Type = ContentType.Png, Width = 1200 },
        new OpenGraphContactData(Application.StreetAddress, Application.Locality, Application.PostalCode, Application.Country)
        {
            Email = Application.Email,
            Phone = Application.Phone,
            Website = Url.AbsoluteRouteUrl(AgendaControllerRoute.GetDelete)
        },
        new OpenGraphLocation(Application.Latitude, Application.Longitude))
    {
        Determiner = OpenGraphDeterminer.Blank,
        SiteName = Application.Name
    };
}

<h2>Eliminar <small>agenda</small></h2>

<h3>¿Estás seguro?</h3>
<hr class="hrSinMarginTop" />
<div class="content-personalizado">

    <dl class="dl-horizontal">
        <dt>
            @Html.Raw("Profesional")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EspecialidadesProfesional.Profesional.Nombre)
            @Html.DisplayFor(model => model.EspecialidadesProfesional.Profesional.Apellido)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.EspecialidadProfesionalId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EspecialidadesProfesional.Especialidad.descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoDiaId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoDia.descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fecha_desde)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fecha_desde)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fecha_hasta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fecha_hasta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.hora_desde)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.hora_desde)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.hora_hasta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.hora_hasta)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-group text-right paddingLeftRight_15">
            <div class="form-actions no-color">
                <button type="submit" class="btn btn-danger">
                    <i class="fa fa-trash-o"></i>
                    Eliminar
                </button>
            </div>
        </div>
    }
    <div>
        <a class="btn btn-sm" href="@Url.Action("Index", "Agenda")">
            <i class="fa fa-chevron-circle-left"></i>
            Volver al listado
        </a>
    </div>
</div>