4TO/MCGA/TPs/UAI-MCGA-SistemaTurnosMedico-master/MCGA.WebSite/Controllers/AfiliadoController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MCGA.Constants;
using MCGA.Entities;
using MCGA.UI.Process;
using PagedList;

namespace MCGA.WebSite.Controllers
{
	[Authorize]
	public class AfiliadoController : Controller
    {
        private AfiliadoProcess process = new AfiliadoProcess();
		private EstadoCivilProcess estadoCivilProcess = new EstadoCivilProcess();
		private PlanProcess planProcess = new PlanProcess();
		private TipoDocumentoProcess tipoDocumentoProcess = new TipoDocumentoProcess();
		private TipoSexoProcess tipoSexoProcess = new TipoSexoProcess();

		public FileResult ExportExcel()
		{
			string[] aColumnas = { "Nombre", "Apellido", "Tipo de documento", "Nº de documento", "Dirección", "Teléfono", "Email", "Sexo", "Fecha de nacimiento", "Estado civil", "Nº de afiliado", "Plan" };
			List<dynamic> lstDatos = process.GetAll().OrderBy(o => o.Nombre).ThenBy(o => o.Apellido).Select(o => new { o.Nombre, o.Apellido, o.TipoDocumento.descripcion, o.Numero, o.Direccion, o.Telefono, o.Email, Sexo = o.TipoSexo.descripcion, FechaNacimiento = o.FechaNacimiento.ToShortDateString(), EstadoCivil = o.EstadoCivil.descripcion, o.NumeroAfiliado, Plan = o.Plan.descripcion }).ToList<dynamic>();
			return File(new Framework.ExportExcel().ExportarExcel(aColumnas, lstDatos), "application/vnd.ms-excel", "Listado de afiliados.xls");
		}

		public JsonResult GetAfiliado(string Areas, string term = "")
		{
			var lista = process.GetAll().Where(o => o.Nombre.ToUpper().Contains(term.ToUpper()) || o.Apellido.ToUpper().Contains(term.ToUpper())).OrderBy(o => o.Nombre).OrderBy(o => o.Apellido).Select(o => new { Id = o.Id, Name = string.Format("{0} {1} Nº {2} ({3} {4})", o.Nombre, o.Apellido, o.NumeroAfiliado, o.TipoDocumento.descripcion, o.Numero) }).ToList();
			return Json(lista, JsonRequestBehavior.AllowGet);
		}

		// GET: Afiliado
		[Route("listado-afiliado", Name = AfiliadoControllerRoute.GetIndex)]
		public ActionResult Index(int? page)
        {
			var afiliado = process.GetAll();
			int pageSize = int.Parse(ConfigurationManager.AppSettings.Get("CantidadFilasPagina"));
			int pageNumber = (page ?? 1);
            return View(afiliado.ToPagedList(pageNumber, pageSize));
        }

		// GET: Afiliado/Create
		[Route("agregar-afiliado", Name = AfiliadoControllerRoute.GetCreate)]
		public ActionResult Create()
        {
            ViewBag.EstadoCivilId = new SelectList(estadoCivilProcess.GetAll(), "Id", "descripcion");
            ViewBag.PlanId = new SelectList(planProcess.GetAll(), "Id", "descripcion");
            ViewBag.TipoDocumentoId = new SelectList(tipoDocumentoProcess.GetAll(), "Id", "descripcion");
            ViewBag.TipoSexoId = new SelectList(tipoSexoProcess.GetAll(), "Id", "descripcion");
            return View();
        }

        // POST: Afiliado/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
		[Route("agregar-afiliado", Name = AfiliadoControllerRoute.PostCreate)]
		public ActionResult Create([Bind(Include = "Id,Nombre,Apellido,TipoDocumentoId,Numero,Direccion,Telefono,Email,TipoSexoId,FechaNacimiento,EstadoCivilId,NumeroAfiliado,PlanId,Habilitado")] Afiliado afiliado)
        {
            if (ModelState.IsValid)
            {
				process.Add(afiliado);
                return RedirectToAction("Index");
            }

            ViewBag.EstadoCivilId = new SelectList(estadoCivilProcess.GetAll(), "Id", "descripcion", afiliado.EstadoCivilId);
            ViewBag.PlanId = new SelectList(planProcess.GetAll(), "Id", "descripcion", afiliado.PlanId);
            ViewBag.TipoDocumentoId = new SelectList(tipoDocumentoProcess.GetAll(), "Id", "descripcion", afiliado.TipoDocumentoId);
            ViewBag.TipoSexoId = new SelectList(tipoSexoProcess.GetAll(), "Id", "descripcion", afiliado.TipoSexoId);
            return View(afiliado);
        }

		// GET: Afiliado/Edit/5
		[Route("editar-afiliado", Name = AfiliadoControllerRoute.GetEdit)]
		public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Afiliado afiliado = process.GetById(id);
            if (afiliado == null)
            {
                return HttpNotFound();
            }
            ViewBag.EstadoCivilId = new SelectList(estadoCivilProcess.GetAll(), "Id", "descripcion", afiliado.EstadoCivilId);
            ViewBag.PlanId = new SelectList(planProcess.GetAll(), "Id", "descripcion", afiliado.PlanId);
            ViewBag.TipoDocumentoId = new SelectList(tipoDocumentoProcess.GetAll(), "Id", "descripcion", afiliado.TipoDocumentoId);
            ViewBag.TipoSexoId = new SelectList(tipoSexoProcess.GetAll(), "Id", "descripcion", afiliado.TipoSexoId);
            return View(afiliado);
        }

        // POST: Afiliado/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
		[Route("editar-afiliado", Name = AfiliadoControllerRoute.PostEdit)]
		public ActionResult Edit([Bind(Include = "Id,Nombre,Apellido,TipoDocumentoId,Numero,Direccion,Telefono,Email,TipoSexoId,FechaNacimiento,EstadoCivilId,NumeroAfiliado,PlanId,Habilitado")] Afiliado afiliado)
        {
            if (ModelState.IsValid)
            {
				process.Edit(afiliado);
                return RedirectToAction("Index");
            }
            ViewBag.EstadoCivilId = new SelectList(estadoCivilProcess.GetAll(), "Id", "descripcion", afiliado.EstadoCivilId);
            ViewBag.PlanId = new SelectList(planProcess.GetAll(), "Id", "descripcion", afiliado.PlanId);
            ViewBag.TipoDocumentoId = new SelectList(tipoDocumentoProcess.GetAll(), "Id", "descripcion", afiliado.TipoDocumentoId);
            ViewBag.TipoSexoId = new SelectList(tipoSexoProcess.GetAll(), "Id", "descripcion", afiliado.TipoSexoId);
            return View(afiliado);
        }

		// GET: Afiliado/Delete/5
		[Route("eliminar-afiliado", Name = AfiliadoControllerRoute.GetDelete)]
		public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Afiliado afiliado = process.GetById(id);
            if (afiliado == null)
            {
                return HttpNotFound();
            }
            return View(afiliado);
        }

        // POST: Afiliado/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
		[Route("eliminar-afiliado", Name = AfiliadoControllerRoute.PostDelete)]
		public ActionResult DeleteConfirmed(int id)
        {
            Afiliado afiliado = process.GetById(id);
            process.Remove(afiliado);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
				process.Dispose();
				estadoCivilProcess.Dispose();
				planProcess.Dispose();
				tipoDocumentoProcess.Dispose();
				tipoSexoProcess.Dispose();
			}
            base.Dispose(disposing);
        }
    }
}

4TO/MCGA/TPs/UAI-MCGA-SistemaTurnosMedico-master/MCGA.WebSite/Controllers/AtencionController.cs
using MCGA.Constants;
using MCGA.Entities;
using MCGA.UI.Process;
using PagedList;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MCGA.WebSite.Controllers
{
	[Authorize]
    public class AtencionController : Controller
    {
		private AtencionProcess atencionProcess = new AtencionProcess();
		private AfiliadoProcess afiliadoProcess = new AfiliadoProcess();

		// GET: Atencion
		[Route("atencion-paciente", Name = AtencionControllerRoute.GetList)]
		public ActionResult List(int afiliadoId, int? page)
		{
			Afiliado afiliado = afiliadoProcess.GetById(afiliadoId);
			ViewBag.AfiliadoId = afiliado.Id;
			ViewBag.Afiliado = string.Format("{0} {1} Nº {2} ({3} {4})", afiliado.Nombre, afiliado.Apellido, afiliado.NumeroAfiliado, afiliado.TipoDocumento.descripcion, afiliado.Numero);
			var atencion = atencionProcess.GetAll().Where(o=> o.Turno.AfiliadoId == afiliado.Id).ToList();
			int pageSize = int.Parse(ConfigurationManager.AppSettings.Get("CantidadFilasPagina"));
			int pageNumber = (page ?? 1);
			return View(atencion.ToPagedList(pageNumber, pageSize));
		}


		protected override void Dispose(bool disposing)
		{
			if (disposing)
			{
				atencionProcess.Dispose();
			}
			base.Dispose(disposing);
		}
	}
}

4TO/MCGA/TPs/UAI-MCGA-SistemaTurnosMedico-master/MCGA.WebSite/Views/Afiliado/Create.cshtml
@model MCGA.Entities.Afiliado
@{
                /**/

                ViewBag.Title = "Afiliado";
                ViewBag.Description = "En esta página vamos a poder agregar afiliados del sistema.";
                ViewBag.Author = Application.Name;
                ViewBag.ReferrerMode = ReferrerMode.OriginWhenCrossOrigin;
                ViewBag.TwitterCard = new SummaryLargeImageTwitterCard("@TwitterCard");
                ViewBag.OpenGraph = new OpenGraphBusiness(
                    ViewBag.Title,
                    new OpenGraphImage(Url.AbsoluteContent("~/fonts/icons/open-graph-1200x630.png")) { Height = 630, Type = ContentType.Png, Width = 1200 },
                    new OpenGraphContactData(Application.StreetAddress, Application.Locality, Application.PostalCode, Application.Country)
                    {
                        Email = Application.Email,
                        Phone = Application.Phone,
                        Website = Url.AbsoluteRouteUrl(AfiliadoControllerRoute.GetCreate)
                    },
                    new OpenGraphLocation(Application.Latitude, Application.Longitude))
                {
                    Determiner = OpenGraphDeterminer.Blank,
                    SiteName = Application.Name
                };
}
<h2>Nuevo <small>afiliado</small> </h2>
<hr class="hrSinMarginTop" />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal content-personalizado">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apellido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoDocumentoId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TipoDocumentoId", null, "-Seleccionar tipo de documento-", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TipoDocumentoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Numero, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Numero, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Numero, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoSexoId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TipoSexoId", null, "-Seleccionar sexo-", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TipoSexoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaNacimiento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaNacimiento, new { htmlAttributes = new { @class = "form-control", @max = DateTime.Now.ToString("yyyy-MM-dd"), @min = "1900-01-01" } })
                @Html.ValidationMessageFor(model => model.FechaNacimiento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EstadoCivilId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EstadoCivilId", null, "-Seleccionar estado civil-", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EstadoCivilId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumeroAfiliado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumeroAfiliado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumeroAfiliado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PlanId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PlanId", null, "-Seleccionar plan-", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PlanId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Habilitado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Habilitado)
                    @Html.ValidationMessageFor(model => model.Habilitado, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group text-right paddingLeftRight_15">
            <button type="submit" class="btn btn-primary">
                <i class="fa fa-check-circle"></i>
                Guardar
            </button>
        </div>
    </div>
}

<div>
    <a class="btn btn-sm" href="@Url.Action("Index", "Afiliado")">
        <i class="fa fa-chevron-circle-left"></i>
        Volver al listado
    </a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

4TO/MCGA/TPs/UAI-MCGA-SistemaTurnosMedico-master/MCGA.WebSite/Views/Afiliado/Delete.cshtml
@model MCGA.Entities.Afiliado
@{
    ViewBag.Title = "Profesional";
    ViewBag.Description = "En esta página vamos a poder eliminar afiliados del sistema.";
    ViewBag.Author = Application.Name;
    ViewBag.ReferrerMode = ReferrerMode.OriginWhenCrossOrigin;
    ViewBag.TwitterCard = new SummaryLargeImageTwitterCard("@TwitterCard");
    ViewBag.OpenGraph = new OpenGraphBusiness(
        ViewBag.Title,
        new OpenGraphImage(Url.AbsoluteContent("~/fonts/icons/open-graph-1200x630.png")) { Height = 630, Type = ContentType.Png, Width = 1200 },
        new OpenGraphContactData(Application.StreetAddress, Application.Locality, Application.PostalCode, Application.Country)
        {
            Email = Application.Email,
            Phone = Application.Phone,
            Website = Url.AbsoluteRouteUrl(AfiliadoControllerRoute.GetDelete)
        },
        new OpenGraphLocation(Application.Latitude, Application.Longitude))
    {
        Determiner = OpenGraphDeterminer.Blank,
        SiteName = Application.Name
    };
}

<h2>Eliminar <small>afiliado</small></h2>

<h3>¿Estás seguro?</h3>
<hr class="hrSinMarginTop" />
<div class="content-personalizado">

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apellido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoDocumentoId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoDocumento.descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Numero)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Numero)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Direccion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoSexoId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoSexo.descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaNacimiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EstadoCivilId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EstadoCivil.descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumeroAfiliado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumeroAfiliado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PlanId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Plan.descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Habilitado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Habilitado)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-group text-right paddingLeftRight_15">
            <div class="form-actions no-color">
                <button type="submit" class="btn btn-danger">
                    <i class="fa fa-trash-o"></i>
                    Eliminar
                </button>
            </div>
        </div>
    }
</div>
<div>
    <a class="btn btn-sm" href="@Url.Action("Index", "Afiliado")">
        <i class="fa fa-chevron-circle-left"></i>
        Volver al listado
    </a>
</div>

4TO/MCGA/TPs/UAI-MCGA-SistemaTurnosMedico-master/MCGA.WebSite/Views/Afiliado/Index.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<MCGA.Entities.Afiliado>

@{
    ViewBag.Title = "Afiliado";
    ViewBag.Description = "En esta página vamos a poder gestionar los afiliados del sistema.";
    ViewBag.Author = Application.Name;
    ViewBag.ReferrerMode = ReferrerMode.OriginWhenCrossOrigin;
    ViewBag.TwitterCard = new SummaryLargeImageTwitterCard("@TwitterCard");
    ViewBag.OpenGraph = new OpenGraphBusiness(
        ViewBag.Title,
        new OpenGraphImage(Url.AbsoluteContent("~/fonts/icons/open-graph-1200x630.png")) { Height = 630, Type = ContentType.Png, Width = 1200 },
        new OpenGraphContactData(Application.StreetAddress, Application.Locality, Application.PostalCode, Application.Country)
        {
            Email = Application.Email,
            Phone = Application.Phone,
            Website = Url.AbsoluteRouteUrl(AfiliadoControllerRoute.GetIndex)
        },
        new OpenGraphLocation(Application.Latitude, Application.Longitude))
    {
        Determiner = OpenGraphDeterminer.Blank,
        SiteName = Application.Name
    };
}

<div class="row">
    <div class="col-lg-8 col-md-8 col-sm-12">
        <h2>
            Afiliado
        </h2>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-12">
        <div class="float-lg-right float-md-right float-sm-none">
            <div class="btn-group" role="group">
                <a title="Agregar afiliado" class="btn btn-sm btn-primary" href="@Url.Action("Create", "Afiliado")">
                    <i class="fa fa-plus-circle"></i>
                    Agregar
                </a>
                <a title="Descargar a Excel" class="btn btn-sm btn-success" href="@Url.Action("ExportExcel", "Afiliado")">
                    <i class="fa fa-download"></i>
                </a>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <div class="table-responsive">
            <table class="table table-sm table-light table-bordered">
                <thead class="thead-light">
                    <tr>
                        <th>
                            @Html.Raw("Nombre completo")
                        </th>
                        <th>
                            @Html.Raw("Tipo de documento") 
                        </th>
                        <th>
                            @Html.Raw("Nº de documento")
                        </th>
                        <th>
                            @Html.Raw("Dirección")
                        </th>
                        <th>
                            @Html.Raw("Teléfono")
                        </th>
                        <th>
                            @Html.Raw("Email")
                        </th>
                        <th>
                            @Html.Raw("Sexo")
                        </th>
                        <th>
                            @Html.Raw("Fecha de nacimiento")
                        </th>
                        <th>
                            @Html.Raw("Estado civil")
                        </th>
                        <th>
                            @Html.Raw("Nº de afiliado")
                        </th>
                        <th>
                            @Html.Raw("Plan")
                        </th>
                        <th>
                            @Html.Raw("Habilitado")
                        </th>
                        <th style="width:10%;"></th>
                    </tr>
                </thead>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Nombre) @Html.DisplayFor(modelItem => item.Apellido)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TipoDocumento.descripcion)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Numero)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Direccion)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Telefono)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Email)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TipoSexo.descripcion)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FechaNacimiento)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.EstadoCivil.descripcion)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NumeroAfiliado)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Plan.descripcion)
                        </td>
                        <td>
                            @if (item.Habilitado)
                            {
                                <span>SI</span>
                            }
                            else
                            {
                                <span>NO</span>
                            }
                        </td>
                        <td>
                            <div class="float-right">
                                <div class="btn-group" role="group">
                                    <a class="btn btn-secondary btn-sm" title="Editar" href="@Url.Action("Edit", "Afiliado",new { id = item.Id })">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                    <a class="btn btn-info btn-sm" title="Editar" href="@Url.Action("List", "Atencion",new { afiliadoId = item.Id })">
                                        <i class="fa fa-list-ul"></i>
                                    </a>
                                    <a class="btn btn-dark btn-sm" title="Datos adicionales" href="@Url.Action("Create", "DatoAdicionalAfiliado",new { afiliadoId = item.Id })">
                                        <i class="fa fa-file-text-o"></i>
                                    </a>
                                    <a class="btn btn-danger btn-sm" title="Eliminar" href="@Url.Action("Delete", "Afiliado",new { id = item.Id })">
                                        <i class="fa fa-trash-o"></i>
                                    </a>
                                </div>
                            </div>
                        </td>
                    </tr>
                }
            </table>
        </div>
    </div>
</div>

@Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
<p class="text-center">
    Página <strong>@(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)</strong> de <strong>@Model.PageCount</strong>
</p>

@section Scripts {
    <script>
        $(document).ready(function () {
            $('table').stacktable();
        });
    </script>
}