4TO/MCGA/TPs/UAI-MCGA-SistemaTurnosMedico-master/MCGA.WebSite/Controllers/TipoEspecialidadController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MCGA.Constants;
using MCGA.Entities;
using MCGA.UI.Process;
using PagedList;

namespace MCGA.WebSite.Controllers
{
	[Authorize]
	public class TipoEspecialidadController : Controller
    {
        private TipoEspecialidadProcess process = new TipoEspecialidadProcess();

		public FileResult ExportExcel()
		{
			string[] aColumnas = { "Descripción" };
			List<dynamic> lstDatos = process.GetAll().OrderBy(o => o.descripcion).Select(o => new { o.descripcion }).ToList<dynamic>();
			return File(new Framework.ExportExcel().ExportarExcel(aColumnas, lstDatos), "application/vnd.ms-excel", "Listado de tipos de especialidad.xls");
		}

		// GET: TipoEspecialidad
		[Route("listado-tipo-especialidad", Name = TipoEspecialidadControllerRoute.GetIndex)]
		public ActionResult Index(int? page)
        {
			var tipoEspecialidad = process.GetAll();
			int pageSize = int.Parse(ConfigurationManager.AppSettings.Get("CantidadFilasPagina"));
			int pageNumber = (page ?? 1);
			return View(tipoEspecialidad.ToPagedList(pageNumber, pageSize));
        }

		// GET: TipoEspecialidad/Create
		[Route("agregar-tipo-especialidad", Name = TipoEspecialidadControllerRoute.GetCreate)]
		public ActionResult Create()
        {
            return View(TipoEspecialidadControllerAction.Create);
        }

        // POST: TipoEspecialidad/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
		[Route("agregar-tipo-especialidad", Name = TipoEspecialidadControllerRoute.PostCreate)]
		public ActionResult Create([Bind(Include = "Id,descripcion")] TipoEspecialidad tipoEspecialidad)
        {
            if (ModelState.IsValid)
            {
				process.Add(tipoEspecialidad);
                return RedirectToAction("Index");
            }
			return View(TipoEspecialidadControllerAction.Create, tipoEspecialidad);
		}

		// GET: TipoEspecialidad/Edit/5
		[Route("editar-tipo-especialidad", Name = TipoEspecialidadControllerRoute.GetEdit)]
		public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
			TipoEspecialidad tipoEspecialidad = process.GetById(id);
			if (tipoEspecialidad == null)
            {
                return HttpNotFound();
            }
			return View(TipoEspecialidadControllerAction.Edit, tipoEspecialidad);
        }

        // POST: TipoEspecialidad/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
		[Route("editar-tipo-especialidad", Name = TipoEspecialidadControllerRoute.PostEdit)]
		public ActionResult Edit([Bind(Include = "Id,descripcion")] TipoEspecialidad tipoEspecialidad)
        {
            if (ModelState.IsValid)
            {
				process.Edit(tipoEspecialidad);
                return RedirectToAction("Index");
            }
			return View(TipoEspecialidadControllerAction.Edit, tipoEspecialidad);
		}

		// GET: TipoEspecialidad/Delete/5
		[Route("eliminar-tipo-especialidad", Name = TipoEspecialidadControllerRoute.GetDelete)]
		public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
			TipoEspecialidad tipoEspecialidad = process.GetById(id);
			if (tipoEspecialidad == null)
            {
                return HttpNotFound();
            }
			return View(TipoEspecialidadControllerAction.Delete, tipoEspecialidad);
        }

        // POST: TipoEspecialidad/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
		[Route("eliminar-tipo-especialidad", Name = TipoEspecialidadControllerRoute.PostDelete)]
		public ActionResult DeleteConfirmed(int id)
        {
			TipoEspecialidad tipoEspecialidad = process.GetById(id);
			process.Remove(tipoEspecialidad);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
				process.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

4TO/MCGA/TPs/UAI-MCGA-SistemaTurnosMedico-master/MCGA.WebSite/Views/TipoEspecialidad/Create.cshtml
@model MCGA.Entities.TipoEspecialidad
@{
    ViewBag.Title = "Tipo de especialidad";
    ViewBag.Description = "En esta página vamos a poder agregar tipos de especialidad del sistema.";
    ViewBag.Author = Application.Name;
    ViewBag.ReferrerMode = ReferrerMode.OriginWhenCrossOrigin;
    ViewBag.TwitterCard = new SummaryLargeImageTwitterCard("@TwitterCard");
    ViewBag.OpenGraph = new OpenGraphBusiness(
        ViewBag.Title,
        new OpenGraphImage(Url.AbsoluteContent("~/fonts/icons/open-graph-1200x630.png")) { Height = 630, Type = ContentType.Png, Width = 1200 },
        new OpenGraphContactData(Application.StreetAddress, Application.Locality, Application.PostalCode, Application.Country)
        {
            Email = Application.Email,
            Phone = Application.Phone,
            Website = Url.AbsoluteRouteUrl(TipoEspecialidadControllerRoute.GetCreate)
        },
        new OpenGraphLocation(Application.Latitude, Application.Longitude))
    {
        Determiner = OpenGraphDeterminer.Blank,
        SiteName = Application.Name
    };
}
<h2>Nuevo <small>tipo de especialidad</small> </h2>
<hr class="hrSinMarginTop" />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal content-personalizado">
        
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.descripcion, "Descripción", htmlAttributes: new { @class = "control-label col-md-12" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group text-right paddingLeftRight_15">
            <button type="submit" class="btn btn-primary">
                <i class="fa fa-check-circle"></i>
                Guardar
            </button>
        </div>
    </div>
}

<div>
    <a class="btn btn-sm" href="@Url.Action("Index", "TipoEspecialidad")">
        <i class="fa fa-chevron-circle-left"></i>
        Volver al listado
    </a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

4TO/MCGA/TPs/UAI-MCGA-SistemaTurnosMedico-master/MCGA.WebSite/Views/TipoEspecialidad/Delete.cshtml
@model MCGA.Entities.TipoEspecialidad
@{
    ViewBag.Title = "Tipo de especialidad";
    ViewBag.Description = "En esta página vamos a poder eliminar los tipos de especialidad del sistema.";
    ViewBag.Author = Application.Name;
    ViewBag.ReferrerMode = ReferrerMode.OriginWhenCrossOrigin;
    ViewBag.TwitterCard = new SummaryLargeImageTwitterCard("@TwitterCard");
    ViewBag.OpenGraph = new OpenGraphBusiness(
        ViewBag.Title,
        new OpenGraphImage(Url.AbsoluteContent("~/fonts/icons/open-graph-1200x630.png")) { Height = 630, Type = ContentType.Png, Width = 1200 },
        new OpenGraphContactData(Application.StreetAddress, Application.Locality, Application.PostalCode, Application.Country)
        {
            Email = Application.Email,
            Phone = Application.Phone,
            Website = Url.AbsoluteRouteUrl(TipoEspecialidadControllerRoute.GetDelete)
        },
        new OpenGraphLocation(Application.Latitude, Application.Longitude))
    {
        Determiner = OpenGraphDeterminer.Blank,
        SiteName = Application.Name
    };
}
<h2>Eliminar <small>tipo de especialidad</small></h2>
<h3>¿Estás seguro?</h3>
<hr class="hrSinMarginTop" />
<div class="content-personalizado">

    <dl class="dl-horizontal">
        <dt>
            @Html.LabelFor(model => model.descripcion, "Descripción")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descripcion)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-group text-right paddingLeftRight_15">
            <div class="form-actions no-color">
                <button type="submit" class="btn btn-danger">
                    <i class="fa fa-trash-o"></i>
                    Eliminar
                </button>
            </div>
        </div>
    }
    <div>
        <a class="btn btn-sm" href="@Url.Action("Index", "TipoEspecialidad")">
            <i class="fa fa-chevron-circle-left"></i>
            Volver al listado
        </a>
    </div>

</div>

4TO/MCGA/TPs/UAI-MCGA-SistemaTurnosMedico-master/MCGA.WebSite/Views/TipoEspecialidad/Edit.cshtml
@model MCGA.Entities.TipoEspecialidad
@{
    ViewBag.Title = "Tipo de especialidad";
    ViewBag.Description = "En esta página vamos a poder editar los tipos de especialidad del sistema.";
    ViewBag.Author = Application.Name;
    ViewBag.ReferrerMode = ReferrerMode.OriginWhenCrossOrigin;
    ViewBag.TwitterCard = new SummaryLargeImageTwitterCard("@TwitterCard");
    ViewBag.OpenGraph = new OpenGraphBusiness(
        ViewBag.Title,
        new OpenGraphImage(Url.AbsoluteContent("~/fonts/icons/open-graph-1200x630.png")) { Height = 630, Type = ContentType.Png, Width = 1200 },
        new OpenGraphContactData(Application.StreetAddress, Application.Locality, Application.PostalCode, Application.Country)
        {
            Email = Application.Email,
            Phone = Application.Phone,
            Website = Url.AbsoluteRouteUrl(TipoEspecialidadControllerRoute.GetEdit)
        },
        new OpenGraphLocation(Application.Latitude, Application.Longitude))
    {
        Determiner = OpenGraphDeterminer.Blank,
        SiteName = Application.Name
    };
}
<h2>Editar <small>tipo de especialidad</small> </h2>
<hr class="hrSinMarginTop" />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal content-personalizado">

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.descripcion, "Descripción", htmlAttributes: new { @class = "control-label col-md-12" })
        <div class="col-md-12">
            @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group text-right paddingLeftRight_15">
        <button type="submit" class="btn btn-primary">
            <i class="fa fa-check-circle"></i>
            Guardar
        </button>
    </div>
</div>
}

<div>
    <a class="btn btn-sm" href="@Url.Action("Index", "TipoEspecialidad")">
        <i class="fa fa-chevron-circle-left"></i>
        Volver al listado
    </a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

4TO/MCGA/TPs/UAI-MCGA-SistemaTurnosMedico-master/MCGA.WebSite/Views/TipoEspecialidad/Index.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<MCGA.Entities.TipoEspecialidad>
@{
    ViewBag.Title = "Tipo de especialidad";
    ViewBag.Description = "En esta página vamos a poder gestionar los tipos de especialidad del sistema.";
    ViewBag.Author = Application.Name;
    ViewBag.ReferrerMode = ReferrerMode.OriginWhenCrossOrigin;
    ViewBag.TwitterCard = new SummaryLargeImageTwitterCard("@TwitterCard");
    ViewBag.OpenGraph = new OpenGraphBusiness(
        ViewBag.Title,
        new OpenGraphImage(Url.AbsoluteContent("~/fonts/icons/open-graph-1200x630.png")) { Height = 630, Type = ContentType.Png, Width = 1200 },
        new OpenGraphContactData(Application.StreetAddress, Application.Locality, Application.PostalCode, Application.Country)
        {
            Email = Application.Email,
            Phone = Application.Phone,
            Website = Url.AbsoluteRouteUrl(TipoEspecialidadControllerRoute.GetIndex)
        },
        new OpenGraphLocation(Application.Latitude, Application.Longitude))
    {
        Determiner = OpenGraphDeterminer.Blank,
        SiteName = Application.Name
    };
}

<div class="row">
    <div class="col-lg-8 col-md-8 col-sm-12">
        <h2>
            Tipo de especialidad
        </h2>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-12">
        <div class="float-lg-right float-md-right float-sm-none">
            <div class="btn-group" role="group">
                <a title="Agregar tipo de especialidad" class="btn btn-sm btn-primary" href="@Url.Action("Create", "TipoEspecialidad")">
                    <i class="fa fa-plus-circle"></i>
                    Agregar
                </a>
                <a title="Descargar a Excel" class="btn btn-sm btn-success" href="@Url.Action("ExportExcel", "TipoEspecialidad")">
                    <i class="fa fa-download"></i>
                </a>
            </div>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-12">
        <div class="table-responsive">
            <table class="table table-sm table-light table-bordered">
                <thead class="thead-light">
                    <tr>
                        <th style="width:90%;">
                            @Html.Raw("Descripción")
                        </th>
                        <th style="width:10%;"></th>
                    </tr>
                </thead>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.descripcion)
                        </td>
                        <td>
                            <div class="float-right">
                                <div class="btn-group" role="group">
                                    <a class="btn btn-secondary btn-sm" title="Editar" href="@Url.Action("Edit", "TipoEspecialidad",new { id = item.Id })">
                                        <i class="fa fa-edit"></i>
                                        Editar
                                    </a>
                                    <a class="btn btn-danger btn-sm" title="Eliminar" href="@Url.Action("Delete", "TipoEspecialidad",new { id = item.Id })">
                                        <i class="fa fa-trash-o"></i>
                                    </a>
                                </div>
                            </div>
                        </td>
                    </tr>
                }

            </table>
        </div>
    </div>
</div>
@Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
<p class="text-center">
    Página <strong>@(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)</strong> de <strong>@Model.PageCount</strong>
</p>